server:
  port: 8083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.66.22.14:8848
  application:
    name: service-passenger-user

#数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-passenger-user?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root


